name: python-build-app

on:
    push:
        paths:
            - version

permissions:
    contents: write

env:
    APP_NAME: Download-Spotify-Music-with-YouTubeDL-

jobs:
    build_linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
                  echo "APP_VERSION=$(cat version)" >> $GITHUB_ENV

            - name: Install pyinstaller and pillow
              run: pip install pyinstaller pillow

            - name: Build the app
              run: pyinstaller --onefile --clean --windowed --name ${{ env.APP_NAME }}${{ env.APP_VERSION }}-ubuntu --icon assets/icons/img.ico --add-data "assets/icons:assets/icons" app.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.APP_NAME }}${{ env.APP_VERSION }}-ubuntu
                  path: dist/${{ env.APP_NAME }}${{ env.APP_VERSION }}-ubuntu

    build_windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
                  echo "APP_VERSION=$(type version)" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

            - name: Install pyinstaller and pillow
              run: pip install pyinstaller pillow

            - name: Build the app
              run: pyinstaller --onefile --clean --windowed --name ${{ env.APP_NAME }}${{ env.APP_VERSION }}-windows --icon assets/icons/img.ico --add-data "assets/icons:assets/icons" app.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.APP_NAME }}${{ env.APP_VERSION }}-windows.exe
                  path: dist/${{ env.APP_NAME }}${{ env.APP_VERSION }}-windows.exe

    upload_release:
        runs-on: ubuntu-latest

        needs: [build_linux, build_windows]

        steps:
            - uses: actions/checkout@v4

            - name: Get the version
              run: echo "APP_VERSION=$(cat version)" >> $GITHUB_ENV

            - name: Download artifacts Ubuntu
              uses: actions/download-artifact@v4
              with:
                  name: ${{ env.APP_NAME }}${{ env.APP_VERSION }}-ubuntu

            - name: Download artifacts Windows
              uses: actions/download-artifact@v4
              with:
                  name: ${{ env.APP_NAME }}${{ env.APP_VERSION }}-windows.exe

            - name: Create a Release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ env.APP_VERSION }}
                  tag_name: ${{ env.APP_VERSION }}
                  draft: true
                  files: |
                      ${{ env.APP_NAME }}${{ env.APP_VERSION }}-ubuntu
                      ${{ env.APP_NAME }}${{ env.APP_VERSION }}-windows.exe
